language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-25
    - android-25
  licenses:
    - '.+'
    
jdk:
  - oraclejdk8

script:
  ./gradlew build
