language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  ./gradlew build
